authentication_token:
    path: /api/authentication_token
    methods: ['POST']

refresh_authentication_token:
    path: /api/refresh_authentication_token
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: ['POST']